name: CI (Linux)
on:
  workflow_call:
jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm
    - name: Install Rust nightly
      run: rustup toolchain install nightly
    - name: Run tests
      run: cargo +nightly test --target x86_64-unknown-linux-gnu -r --all-targets
      env:
        RUSTFLAGS: -Zsanitizer=address
