name: CI (Linux)
on:
  workflow_call:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Run tests
      run: cargo test -r
