name: CI (Windows)
on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
jobs:
  build:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Update Rust
      run: rustup update stable
    - name: Run tests
      run: cargo test --target ${{ inputs.target }} -r
