name: Development Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
concurrency: ${{ github.ref }}
jobs:
  prebuild:
    name: Pre-build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Check code styles
      run: cargo fmt --check
  build-linux:
    name: Build
    uses: ./.github/workflows/ci-linux.yml
    needs: prebuild
  build-mac:
    name: Build
    uses: ./.github/workflows/ci-mac.yml
    needs: prebuild
  build-windows:
    name: Build
    uses: ./.github/workflows/ci-windows.yml
    needs: prebuild
